version: '3.9'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: mybazaar
      POSTGRES_PASSWORD: mybazaar
      POSTGRES_DB: mybazaar
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mybazaar"]
      interval: 5s
      timeout: 5s
      retries: 10

  server:
    build: ./apps/server
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://mybazaar:mybazaar@db:5432/mybazaar
      SESSION_SECRET: supersecret_dev_change_me
      PORT: 5000
      WS_PORT: 5001
      UPLOAD_DIR: /usr/src/app/uploads
      BASE_URL: http://localhost:5000
    ports:
      - "5000:5000"
      - "5001:5001"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./uploads:/usr/src/app/uploads

  web:
    build: ./apps/web
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_API_URL: http://localhost:5000
      NEXT_TELEMETRY_DISABLED: "1"
    ports:
      - "3000:3000"
    depends_on:
      - server

volumes:
  db_data:
